### ISSUE TITLE
MSBuild and SendGridMail dependency on System.Net.Http, Version=2.0.0.0

### ISSUE THREAD

**Issue by Gwasshoppa** [smurfpandey/sendgrid-csharp-net40#1]
Hi... I am currently having to use SendGridMail .net 4.0 due to one of our projects being in .net 4.0

We are trying to release this using MSBuild.exe to our website through TeamCity.

When I try to package the project I get the following error.

[ResolveAssemblyReference] C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(1605, 5): warning MSB3268: The primary reference "SendGridMail" could not be resolved because it has an indirect dependency on the framework assembly "System.Net.Http, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" which could not be resolved in the currently targeted framework. ".NETFramework,Version=v4.0". To resolve this problem, either remove the reference "SendGridMail" or retarget your application to a framework version which contains "System.Net.Http, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".

My System.Net.Http is version 4.0.0 which is the standard .net 4.0.30319. It appears that the System.Net.Http reference in SendGridMail .net 4.0 is referencing System.Net.Http version 2.0.0.

Is there a way to correct this reference?

Regards
Gwasshoppa

**Comment by smurfpandey** [comment]
Looks like the problem is with .net 4.0, can you try the solution mentioned here: http://sharpfellows.com/post/Compile-can-not-resolve-SystemNetHttp-in-currently-targeted-framework

**Comment by Gwasshoppa** [comment]
Brilliant... that fixed the issue. Thanks for the quick response :)

Gwasshoppa
